matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      script:
        - cd MANO-API
        - gradle build

    - language: php
      php:
        - 7.0
      script:
        - ./bin/check_php_syntax.sh

    - language: minimal
      services: docker
      script:
        - ./bin/build_docker_containers.sh
        - ./bin/run_docker_compose.sh
        - ./tests/test_login.sh
        - ./tests/test_lookup_devices.sh
