matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      script:
        - cd MANO-API
        - gradle build

    - language: php
      php:
        - 7.2
      script:
        - ./bin/check_php_syntax.sh

    - language: minimal
      services: docker
      script:
        - ./bin/build_docker_containers.sh
        - ./bin/run_docker_compose.sh
        - ./bin/run_tests.sh


# use travis cache for gradle or risk maven-central blacklisting
# https://docs.travis-ci.com/user/languages/java/#caching

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
