matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      script:
        - cd MANO-API
        - gradle build

    - language: php
      php:
        - 7.0
      script:
        - ./bin/check_php_syntax.sh

    - services: docker
      script:
        - ./bin/run_docker_compose.sh
