version: "2"

services:

  mano-api:
    image: ubi.mano.api:1.0
    build:
      context: ..
      dockerfile: docker/mano-api/Dockerfile

    hostname: mano
    ports:
    - "8666:8666"
    networks: [ ubi.network ]
    depends_on: [ "msa" ]

  tests:
    image: ubi.mano.tests:1.0
    build:
      context: ..
      dockerfile: docker/tests/Dockerfile

    hostname: tests
    networks: [ ubi.network ]
    depends_on: [ "mano-api" ]

  msa:
    image: ubi.mano.msa:1.0
    build:
      context: ..
      dockerfile: docker/msa/Dockerfile

    hostname: msa
    ports:
    - "80:80"
    - "443:443"
    networks:
      ubi.network:
        ipv4_address: 172.18.0.2


networks:
  ubi.network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
